### ISSUE TITLE
Questions about files for running Template-GUI

### ISSUE THREAD

**Issue by jinhyunglee** [cortex-lab/KiloSort#100]
Hello KiloSort team,
I have some questions about files required for running template-GUI.
I currently have spike train and recording and would like to visualize the result.

If you can help answering the questions below, I would really appreciate.

1. amplitudes.npy : what is the purpose of this one? can I just set it to 1 for all spikes?

2. pc_features.npy and pc_feature_ind.npy: I want to make sure that I understood correctly. Is nPCFeatures the number of channels per spike? If this is correct, pc_feature_ind should have the size of [nSpikes, nPCFeatures]. Also, the example given in the description should be pc_features[123,1,5] is the projection of the 123rd spike onto the 1st PC on the channel given by
pc_feature_ind[123,5]? 

3. How do I calculate similarity score in similar_templates.npy?

4.I am confused about template_features.npy and template_feature_ind.npy but I assume answer to #2 applies here too.

5. whitening_mat_inv.npy is just a pure inverse of whitening_mat.npy?

Thank you so much in advance!

**Comment by nsteinme** [comment]
Thanks for your question, but if I understand correctly you would just like to use visualization features, is that correct? If so, could you please re-post this issue on Phy-contrib's github page? Phy does visualization, Kilosort just does automatic-stage sorting. 
https://github.com/kwikteam/phy-contrib/issues

Also please see this documentation for some of the answers. 
http://phy-contrib.readthedocs.io/en/latest/template-gui/
