### ISSUE TITLE
New kind of crash (ram related?)

### ISSUE THREAD

**Issue by danielnee2** [cortex-lab/KiloSort#106]
Hi All:
I read through all the discussion threads and 
did not see the same error I got here.

![error_memory2](https://user-images.githubusercontent.com/13595756/33798927-63a9c450-dcd6-11e7-9eda-1f364c275a71.png)

We are using a 256 channel (Multichannel systems) MEA for recording,
and I convert the data into .dat binary files for kilosort input.
At shorter recordings kilosort works fine,
but when the .dat file is exceeds 90 Gbs at Nfilt = 256,
it crashes at line 271 during the preprocess.

I am using a Win10 system with 32 Gb ram. Anyone suffers from similar issues?
Thanks

**Comment by marius10p** [comment]
The initialization clustering seems to keep expanding the set of detected spikes. Either you have a very rich recording, or some spike threshold settings are set too low. Increase the magnitude of the threshold for example with 

ops.spkTh           = -6;      % spike threshold in standard deviations (4)		

or the options below. Alternatively, try just turning off the initialization and see if you get significantly worse results. Usually you won't see a big difference.

**Comment by danielnee2** [comment]
Hi Marius:
Thanks so much for the suggestions. 
I tried the turn off  initialization method and it works fine without obvious detrimental effect on spike detection.
The recording is very rich indeed and may be the reason that crash the initialization clustering.
Would be nice if later kilosort versions can adapt to high firing rate recordings as well.
