### ISSUE TITLE
merging_score with zeros as inputs

### ISSUE THREAD

**Issue by ferchaure** [cortex-lab/KiloSort#114]
Hi, I get this error in one of many datasets I was testing 
> Nonfinite endpoints or increment for colon operator in index.
> 
> Error in merging_score (line 22)
> steps = sum(hs1(1:m1)<mmax/troughToPeakRatio) + ...
> 
> Error in merge_posthoc2 (line 89)
>             mo = merging_score(f1old - f2old, f1new-f2new, ops.fracse);
> 
> Error in kilosort_carlos (line 90)
> rez = merge_posthoc2(rez);
> 
Looking inside the code the error appears because at merge_posthoc2.m the first and second inputs of  `mo = merging_score(f1old - f2old, f1new-f2new, ops.fracse);` are all zeros

Do you have an idea how to fix this?

**Comment by marius10p** [comment]
Sometimes that merging code fails and I am not sure why. We are not going to support that functionality going forward, since Kilosort2 is much more capable to make automated merges without these posthoc steps.
