### ISSUE TITLE
sanitize inputs

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/KiloSort#127]
1) Check that ops.Nfilt is a multiple of 32, set to next largest such value if not and give warning
2) Check that ops.NChan matches the number of connected channels in the channel map and correct it if not (or, remove this as a parameter and determine it on load). 
3) Check that the number of bytes in the file is a multiple of ops.NChanTOT. If not, check whether it is a multiple of any nearby values. Then give a useful error message, including a suggestion about what NChanTOT might be if a suitable value was found. 
4) Optional - Provide a function that will load a few channels from different points in the file and plot the traces, so that users can visually check that data is getting loaded correctly. E.g. load the first 16 channels from near the beginning of the file, the middle 16 channels from near the middle of the file, and last 16 channels from near the end of the file, in 200ms snippets each, and plot these. if ops.makeplots, then make these by default. 

@marius10p Assign me if you are ok with me doing these?

**Comment by marius10p** [comment]
Sounds good, thanks!
