### ISSUE TITLE
Where is "mexMPregMU.m" file? 

### ISSUE THREAD

**Issue by Ehsan-Negahbani** [cortex-lab/KiloSort#131]
Hi,

I would like to first thank you for this valuable contribution. I also have a question and wanted to know your thoughts on this:
Matlab can not find "mexMPregMU.m" which is called in line 211 of "fitTemplates.m".

I appreciate any help to resolve this issue.

Ehsan

**Comment by marius10p** [comment]
Hi Ehsan,

The function you are looking for is mexMPregMU.cu, which is a CUDA function that needs to be compiled first running mexGPUall from the CUDA folder. If you do not have a CUDA enabled GPU, then please set ops.GPU = 0 and it will use the CPU, but it will be much slower. 

For more information about setting up Kilosort, please read the readme on the main repository page. 

Let us know if there is anything else we can help with. 

- Marius

**Comment by Ehsan-Negahbani** [comment]
Thanks a lot Marius, running mexGPUall solved the problem.
