### ISSUE TITLE
Filtfilt instead of filter?

### ISSUE THREAD

**Issue by apaks** [cortex-lab/KiloSort#134]
Hello,

I wanted to ask whether you tried to use filtfilt (instead of filter) in pre processing step? I was wondering whether it will affect clustering and waveform shape. 

Thanks,

**Comment by rishidhingra** [comment]
The code explicitly filters in the forward and backward direction as it is. filtfilt will give the same answer.

**Comment by marius10p** [comment]
This was because filtfilt needed double variables as inputs (I think it still does?). Closing the issue.
