### ISSUE TITLE
Usage of parameters

### ISSUE THREAD

**Issue by Alkohost** [cortex-lab/KiloSort#136]
Hello.

I use Kilosort for high-density 32-channel recordings by silicone probes. I get more or less beautiful clusters with acceptable waveforms, little bit noisy autocorrelograms, but I confused by relatively high firing rate. It could mean I have at least two neurons in the cluster.  I suppose changing some parameters could be helpfull, but have no ideas what to change for better result.

ops.Th               = [4 10 10];    % threshold for detecting spikes on template-filtered data ([6 12 12])		
ops.lam              = [5 20 20];   % large means amplitudes are forced around the mean ([10 30 30])

Can you please give more detailed tutorial for params selection?
By the way, is isolation distance analysis applicable for cProj?

Thank you.

**Comment by nsteinme** [comment]
If you think Kilosort should have found more clusters, try increasing
ops.Nfilt. You will have to do more merging but it may solve the problem.

**Comment by marius10p** [comment]
If the amplitude distributions look like they extend into the noise, then you could benefit from higher threshold ops.Th.
