### ISSUE TITLE
CUDA fails if Nrank is not set to 3

### ISSUE THREAD

**Issue by warnerwarner** [cortex-lab/KiloSort#140]
If I change the Nrank variable in the config file I receive the CUDA_ADDRESS_ILLEGAL error when it starts optimising the templates. However, I can get the code to run if I disable the GPU usage. Is there another variable I need to change alongside the rank to correct for this?

Thanks,
Tom

**Comment by marius10p** [comment]
Sorry, we have not tested it with Nrank different than 3. Should really not matter much if you increase Nrank.
