### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by stephengv** [cortex-lab/KiloSort#142]
We have been trying to add the  [amplitude histogram](https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/views/amplitude_histogram.py) view to our installation of phy but keep running into an error when we launch Phy, that seems to originate with the attempt to load "AsynchCaller".

![image](https://user-images.githubusercontent.com/38478934/41733825-1c912430-7553-11e8-9ae1-9bb9e2506080.png)

Following the instructions, we have edited the config file, and created a plugin folder in the .phy folder, into which we have placed a text file with the plugin's code, and named that file "amplitude_histogram.py".

Any guidance you can provide would be greatly appreciated.

**Comment by marius10p** [comment]
I think you should ask this in the Phy github page, I don't know the answer.

**Comment by claudiagjou** [comment]
Thanks! I will do that.

**Comment by stephengv** [comment]
Thanks! We will do that.

**Comment by marius10p** [comment]
Closing, since this is a Phy issue.
