### ISSUE TITLE
GPU recommendation

### ISSUE THREAD

**Issue by wehrlab** [cortex-lab/KiloSort#144]
Hi,
do you have recommendations for graphics card? I plan to upgrade my computer to use kilosort for data analysis using Windows 10.

Thanks.

**Comment by marius10p** [comment]
Top of the line GTX card if you can afford it, which will make your investment future proof
1080Ti>1080=1070Ti>1070>1060. Even the 1060 will be breezy up to hundreds of channels.  No AMD, Titan/Tesla is waste of money. Cheers, - Marius

**Comment by wehrlab** [comment]
thanks!
