### ISSUE TITLE
How are spike times calculated?

### ISSUE THREAD

**Issue by angelonc** [cortex-lab/KiloSort#152]
Hi, sorry if this is already covered in the documentation, but I couldn't seem to find it anywhere, and didn't feel like doing a deep dive into the code! I know the spike time outputs are in sample numbers from the continuous trace, but I wasn't sure where in the waveform the sample number is generated (at the peak of the fitted template, template start, end, middle, etc?).

In short, to do some timing tests, I generated some fake spikes with a precise lag after a stimulus event (10ms), but when I actually plot spike rasters of these I am about 2ms off, with the spikes being detected at 12ms.

**Comment by marius10p** [comment]
The spikes are detected where they best match the template, which is roughly at the trough.
