### ISSUE TITLE
Spike time problem

### ISSUE THREAD

**Issue by nicklesica** [cortex-lab/KiloSort#154]
Hi,

There is something strange in my spike times. My data are recorded at 24414.0625 Hz. But when I plot the histogram of the difference  between successive spike times at this resolution, it has strange oscillations at a frequency that is roughly an order of magnitude lower. 

Here is an example histogram:

![image](https://user-images.githubusercontent.com/24247741/44028468-313c0242-9f24-11e8-87a4-bd5a2e995eb9.png)

This happens in all of my recordings. And it happens for both all spike times and individual clusters.

I haven't seen any mention of this in this forum, so perhaps I am doing something wrong, but I can't imagine what. 

Please help!

Thanks,

Nick

**Comment by marius10p** [comment]
Hi Nick,
Just to confirm, these are all the spike times from all neurons, and you are plotting ISI on the x-axis?  That looks like way too many ISIs of 0. I can imagine a few situations: maybe your threshold is set too low (ops.Th), maybe there is some periodic noise at that frequency, or maybe the channel map is not right and the data is not read in correctly. Do the templates look ok? Did you set the number of filters to a multiple of 32? Are there just a few units that contribute to this effect?

**Comment by nsteinme** [comment]
Hmmm, I don't see it in my data, e.g.: 
![image](https://user-images.githubusercontent.com/7590975/44042354-ef2bf7a6-9f17-11e8-97e3-a80b70c52d1c.png)

**Comment by brendonw1** [comment]
Aliasing of some sort??

**Comment by nicklesica** [comment]
<Sigh>

OK, it was just something dumb. Matlab hist doesn't work for integer types so I was converting the spike times to single precision to make the histogram. But that wasn't sufficient precision so the times were getting somehow quantized. Converting to double precision solved the problem.

Thanks!
