### ISSUE TITLE
Template crossing shanks despite kcoords

### ISSUE THREAD

**Issue by clausagerskov** [cortex-lab/KiloSort#156]
Running newest kilosort (commit 0fbe8eb) with the chanMap.mat, master:file and StandardConfig (all files attached) results in templates crossing shanks.

The electrodes used are two 4x4 planer electrodes in two different locations. The final electrode on the second array is used as ground and so is treated as disconnected.
The kcoord variable = [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 NaN];

The two different electrodes should be treated as to independent shanks and be processed separately
![shank_crossing_template](https://user-images.githubusercontent.com/13769591/44261110-e765f880-a216-11e8-90ad-b02613bd3b87.png)

[configfiles.zip](https://github.com/cortex-lab/KiloSort/files/2296819/configfiles.zip)

**Comment by marius10p** [comment]
A fraction of them are supposed to cross shanks to account for noise. Default is 0.2, but you can change it.

**Comment by clausagerskov** [comment]
Thank you for the quick response!
