### ISSUE TITLE
Kilosort output spike_clusters.npy

### ISSUE THREAD

**Issue by rswilliamson** [cortex-lab/KiloSort#17]
At the moment, the spike_clusters.npy file is only created when Phy is run for the first time. It might be useful to have kilosort create this file so that preliminary analysis code can be run on all clusters prior to manual curation.

-Ross

**Comment by nsteinme** [comment]
spike_clusters.npy is identical to spike_templates.npy until you do any
merging or splitting. So: cp spike_templates.npy spike_clusters.npy. Or
duplicate the line in rezToPhy that writes spike_templates.

**Comment by marius10p** [comment]
I duplicated the line in rezToPhy that writes spike_templates. If merge_posthoc2 had been run, these will be used as spike_clusters instead.
