### ISSUE TITLE
Performance on short duration recordings?

### ISSUE THREAD

**Issue by HealeyLab** [cortex-lab/KiloSort#221]
I am trying to connect neurons from one recording to another recording, where the first recording is ~1hr long and the second recording is often less than a minute long. I am worried that when I sort the shorter recording (with the same parameters as the longer one), the spike count is artificially low for neurons with low firing rates. Does anyone have thoughts on this?

**Comment by brendonw1** [comment]
Maybe concatenate the files first then spike sort then separate spikes by
which original file they were in - if you need them separated
