### ISSUE TITLE
biased against narrow wave-shape spikes?

### ISSUE THREAD

**Issue by esiabri** [cortex-lab/KiloSort#235]
Hi, 
thank you for this amazing tool!
I've noticed that it seems that the narrow wave-shape spikes (coming from putative FS neurons) are more probable to be missed. I have attached here two sample snapshots from the Kilosort GUI, as it can be seen spikes with lower amplitudes were deleted while larger narrower spikes are missed. I was wondering if I miss something and I can fix this through some parameters? does it have something to do with the fact they are less probable to be detected on multiple channels?
![Capture1](https://user-images.githubusercontent.com/5842461/117151189-d5419500-ad86-11eb-8895-92a8d41d9683.JPG)
![Capture2](https://user-images.githubusercontent.com/5842461/117151192-d5da2b80-ad86-11eb-8c8d-4c58dfa9d321.JPG)

**Comment by esiabri** [comment]
this was with kilosort 3 so I'll move it to the kilosort 3 repository!

**Comment by cgallimore25** [comment]
> this was with kilosort 3 so I'll move it to the kilosort 3 repository!

@esiabri  I'm finding this same issue in my recordings using KS3.  i know this is an old post, but did you ever figure out a combination of parameters that enable KS to detect these spikes?
