### ISSUE TITLE
Whitened data NOT written to disk

### ISSUE THREAD

**Issue by micheleacox** [cortex-lab/KiloSort#46]
Within preprocessData.m, the fwrite call for the whitened data is imbedded in a for loop (line 207) and an if statement (lines 278-283; see below). 

```
for ibatch = 1:Nbatch
[...]
    if ibatch<=Nbatch_buff
        DATA(:,:,ibatch) = gather_try(datr);
    else
        datcpu  = gather_try(int16(datr));
        fwrite(fidW, datcpu, 'int16');
    end
[...]
end
```

When Nbatch_buff == Nbatch, the fwrite command doesn't actually get executed. In practice, this means the the file on disk, temp_wh.dat, is sized 0 bytes. Is this a problem?

**Comment by marius10p** [comment]
If you have enough RAM to hold  all the data, there will be nothing written to disk. You can control the max amount of RAM with this option

ops.ForceMaxRAMforDat = 20e9; 

Any batches that exceed this limit will be written to disk instead. If you have a fast PCIe SSD, then you won't see much of a speed difference  between RAM and disk.
