### ISSUE TITLE
HDF5 Import (MultiChannel raw data) and file merge

### ISSUE THREAD

**Issue by RoscoeOBrian** [cortex-lab/KiloSort#51]
Hello,
I have raw data from a 60 electrode MultiChannelSystem. Those come in a special MultiChannel format ".msrd". MultiChannel provides a tool to convert those files in HDF5 format.

Is it possible to import those HDF5 format files into Kilosort? 
AND
Is it possible to import multiple files and analyze them all together as a merged file?Since those merged files tend to become very big, it would be even better to get some kind of Unit-file out of every analysis. This file can be used to analyze following files whether the same units on the same electrodes are still present (In addition to possible new ones) or gone.

Greetings

**Comment by marius10p** [comment]
Hi,

Re: formats, we will only support raw binary files. Should be easy to take your data from any format you have and just write it to disk as a binary file. Alternatively, you can figure out where the data gets read into Kilosort, and contribute this functionality yourself. You would only need to change preprocessData.m. 

For your second question, as long as you put them into a binary file, you can still run Kilosort. If your data does not fit in RAM, you can use local storage, ideally a fast SSD. 

Best,
   Marius
