### ISSUE TITLE
make runKilosort a function rather than a script

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/KiloSort#7]
This would allow, for instance, calling it on an array of files; currently not conveniently possible due to the clearvars command. The user could edit runKilosort directly of course, but then they have to merge when you (for instance) add a parameter or something like that. Turning it into a function would be cleaner - variables you intend to keep around that aren't currently in rez could be optional return arguments.

**Comment by marius10p** [comment]
I have instead turned the 3 underlying steps in Kilosort into functions (preprocessData, fitTemplates, fullMPMU) and put all options separately into a configuration file. This makes for a much cleaner master_file, which can be flexibly modified by users for batch processing of multiple experiments.
