### ISSUE TITLE
Cluster Scores

### ISSUE THREAD

**Issue by kkatlowitz** [cortex-lab/KiloSort#73]
Are there analogs of isolation distance, etc. for kilosort templates? In other words, given the new clustering paradigm, how should we think about scoring the quality of our clusters? 

For example, we don't really have noise clusters anymore. 

Thank you,

Vigi Katlowitz

**Comment by nsteinme** [comment]
It is not an easy question; really it is a research problem. But see here
for a start: https://github.com/cortex-lab/sortingQuality

**Comment by kkatlowitz** [comment]
Agreed.
Ok thank you, I will take a look.

Vigi
