### ISSUE TITLE
Channel order is scrambled when clustering?

### ISSUE THREAD

**Issue by eavilao** [cortex-lab/KiloSort#76]
Any time separate clusters in a channel are grouped or marked as multi/good unit or noise, the program scatters the order of the channels so they are arranged by id # instead of channel #. Is there a way to fix this?
Also, occasionally when sorting Kilosort stops automatically changing the channel you are viewing in WaveformView so that it just stays on the same channel, showing noise, as you click through others in ClusterView.

**Comment by nsteinme** [comment]
Am I correct that you are describing things you are seeing when using the phy gui to look at kilosort results? If so, could you please repost the issue on phy's github page, here: https://github.com/kwikteam/phy/issues

I will close the issue but please re-open it if I'm wrong. Thanks -
