### ISSUE TITLE
organisation of functions in repository

### ISSUE THREAD

**Issue by zeeMonkeez** [cortex-lab/KiloSort#79]
Currently, the Kilosort repository pollutes the MATLAB path with many function definitions, some of which are rather generic (such as `shift_data`) or even conflict with MATLAB internal functions (`normc`) and are presumably not meant to be used by end users directly. Would it be possible to make functions that are not intended to be publicly accessible [private](https://ch.mathworks.com/help/matlab/matlab_prog/private-functions.html)? As a consequence, instead of having to add the whole tree to MATLAB's path, only the root folder would have to be added, decluttering the PATH configuration.

**Comment by marius10p** [comment]
If you offer a better solution I can look into it, but dumping all functions into a folder called "private" is not an option. The simple solution is to not add Kilosort to your path at startup. Just add it at the top of your master_file script, and then it won't pollute your path on a non-Kilosort session. 

P.S. "normc" is inside a toolbox, and we did not want to require that toolbox.
