### ISSUE TITLE
Possible for one spike to be in multiple clusters?

### ISSUE THREAD

**Issue by shihaisun** [cortex-lab/KiloSort#89]
Hi KiloSort team,

Just wondering if it's possible for KiloSort to assign one spike into multiple clusters? For example below, could these three clusters share the same spikes? I'm asking because of what the cross correlograms show.

![capture](https://user-images.githubusercontent.com/30403651/31178420-bc65da98-a964-11e7-9686-7ab4eea96c92.PNG)

Thanks,
Scott

**Comment by nsteinme** [comment]
It is possible for kilosort to identify spikes from multiple clusters as
occurring at the same time sample, i.e. kilosort definitely can decide that
cluster 14 and cluster 55 both had a spike at time=10.3432 sec. This will
happen when kilosort identifies a spike of one of them at that time point,
subtracts it away, and finds that the remaining signal still looks like the
spike of the other cluster. This allows it to detect when multiple spikes
really do happen at the same moment in time. I would say that seems likely
to be what's happening here, as the red and blue clearly have different
waveform shapes (red much narrower). In other words, I don't think this is
an error of any kind, I think it is correct behavior. Whether you are
confident enough to interpret the lag=0 CCG bin as meaningful will be up to
you - if it is critical, I suggest you carefully examine the raw data
around these coincident spikes as much as possible and see whether you
believe kilosort has done a good job.

**Comment by shihaisun** [comment]
Thank you so much for the prompt response! Closing the issue.
