### ISSUE TITLE
 Error in fullMPMU (line 144) - Out of memoryon device, but resetting device does not fix it

### ISSUE THREAD

**Issue by englishdaniel** [cortex-lab/KiloSort#92]
Sam Mckenzie and I have been using kilosort for > 1 year now, and just published using it. In the past we were sorting at most 64 channel probes, and were very happy with performance.

Now we are are recording with 256 ch probes, and the first time trying to run kilosort we are getting the following error, even after resetting the gpu with gpuDevice (1). Do you have any suggestions on what we can do? Would one of the 1080 gpu cards solve the issue?
..................

rez = fitTemplates(rez, DATA, uproj);  % fit templates iteratively
Fitting templates
Time 2782s. Optimizing templates ...
Time 8065.99, batch 25401/25416, mu 15.87, neg-err 1113136.851835, NTOT 5725113, n100 10315, n200 6786, n300 4493, n400 3124
>> 
disp('Extracting final spike times')
rez = fullMPMU(rez, DATA);% extract final spike times (overlapping extraction)
Extracting final spike times
Time 8199s. Running the final template matching pass...
Error using gpuArray.zeros
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling
'gpuDevice(1)'.

Error in fullMPMU (line 139)
        data    = gpuArray.zeros(NT, Nfilt, Nrank, 'single');
 
>> gpuDevice(1)

ans = 

  CUDADevice with properties:

                      Name: 'GeForce GTX 980 Ti'
                     Index: 1
         ComputeCapability: '5.2'
            SupportsDouble: 1
             DriverVersion: 8
            ToolkitVersion: 7.5000
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 6.3722e+09
           AvailableMemory: 5.9368e+09
       MultiprocessorCount: 22
              ClockRateKHz: 1291000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

>> 
disp('Extracting final spike times')
rez = fullMPMU(rez, DATA);% extract final spike times (overlapping extraction)
Extracting final spike times
Time 8235s. Running the final template matching pass...
Error using  * 
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling
'gpuDevice(1)'.

Error in fullMPMU (line 144)
...........

DATA variable contains: val =

   Empty array: 32960-by-256-by-0

**Comment by marius10p** [comment]
Sorry, didn't see this. Yes, I think upgrading to 1080Ti would have fixed it, but it depends how many clusters you were asking for.
