### ISSUE TITLE
Error: need more than 1 value to unpack

### ISSUE THREAD

**Issue by vncntprvst** [cortex-lab/KiloSort#95]
Hi,
I ran KiloSort on my data. All seems fine. But when trying to open params.py in phy, I get this error:
`[E] cli:36               An error has occurred (ValueError): need more than 1 value to unpack`
That's a bit cryptic :)
Any help appreciated!
Thanks.

**Comment by nsteinme** [comment]
This one I don't know, but again please do post on phy, and try --debug.
